Instead of calling one function at a time, .agg() lets you apply several simultaneously.

# Basic Imports

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Multiple functions on one column

In [3]:
df.groupby("Pclass")["Fare"].agg(["mean", "min", "max", "count"])

             mean  min       max  count
Pclass
1       84.154687  0.0  512.3292    216
2       20.662183  0.0   73.5000    184
3       13.675550  0.0   69.5500    491

# Different functions on different columns

In [4]:
df.groupby("Pclass").agg(
    avg_age = ("Age" , "mean"),
    avg_fare = ("Fare" , "mean"),
    survival_rate = ("Survived" , "mean"),
    total_passengers = ("PassengerId" , "count")
)

          avg_age   avg_fare  survival_rate  total_passengers
Pclass
1       38.233441  84.154687       0.629630               216
2       29.877630  20.662183       0.472826               184
3       25.140620  13.675550       0.242363               491

The named aggregation syntax new_col_name=("source_col", "function") is the cleanest way to write this — your output columns get proper names.